METER  = 1
METERS = METER
FOOT = 0.3048
FEET = FOOT
CENTIMETER  = METER / 100
CENTIMETERS = CENTIMETER
MILLIMETER  = METER / 1000
MILLIMETERS = MILLIMETER

EPSILON = MILLIMETER * .1
BIG_DISTANCE = 4096 * 64 * METER
